name: private_gitlab_notifier
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.4.3

dependencies:
  http: ^1.2.2
  json_annotation: ^4.9.0
  shelf: ^1.4.2
  shelf_web_socket: ^2.0.0
  web_socket_channel: ^3.0.1

dev_dependencies:
  json_serializable: ^6.8.0
  build_runner: ^2.4.11
  lints: ^3.0.0
  test: ^1.24.0